<?php
/*
 * Catalogo del negozio (lib/shop.php): copricapi, sfondi, bordi e nickname, un oggetto per riga. Si può modificare a mano:
 *  - copricapi: [chiave, nome, prezzo, forma (lib/hats.php), colore a, b, c];
 *  - sfondi e bordi: [chiave, nome, prezzo] (il disegno sta in assets/style.css: classi bgp-<chiave> e brd-<chiave>);
 *  - nickname: [chiave, nome, prezzo] se si compra, oppure [chiave, nome, null, [statistica, soglia, descrizione]] se si sblocca con un obiettivo.
 * Le chiavi sono uniche in tutto il catalogo e lunghe al massimo 16 caratteri (finiscono nel database).
 */
return [
    'hat' => [
        ['cap', 'Cappellino rosso', 40, 'cap', '#ff5a5f', '#c93a40', ''],
        ['h_cap_blu', 'Cappellino blu', 40, 'cap', '#4a90e2', '#2f63b0', ''],
        ['h_cap_verde', 'Cappellino verde', 40, 'cap', '#38d178', '#23a85b', ''],
        ['h_cap_nero', 'Cappellino nero', 50, 'cap', '#3a3450', '#1f1a2e', ''],
        ['h_cap_rosa', 'Cappellino rosa', 40, 'cap', '#ff8fbf', '#e0568f', ''],
        ['h_visiera', 'Visiera bianca', 30, 'visor', '#ffffff', '#e0e0ea', ''],
        ['h_visiera_g', 'Visiera gialla', 30, 'visor', '#ffd23f', '#f0a800', ''],
        ['h_lana_rossa', 'Berretto di lana rosso', 40, 'beanie', '#ff5a5f', '#c93a40', '#ffffff'],
        ['h_lana_blu', 'Berretto di lana blu', 40, 'beanie', '#4a90e2', '#2f63b0', '#ffd23f'],
        ['h_lana_verde', 'Berretto di lana verde', 40, 'beanie', '#38d178', '#23a85b', '#ffffff'],
        ['h_lana_viola', 'Berretto di lana viola', 50, 'beanie', '#a67cf2', '#7a4fd6', '#ffd23f'],
        ['h_bandana_r', 'Bandana rossa', 30, 'bandana', '#ff5a5f', '#ffffff', ''],
        ['h_ninja', 'Fascia da ninja', 50, 'bandana', '#2b2540', '#c0c6d2', ''],
        ['h_fascia_sport', 'Fascia sportiva', 30, 'bandana', '#ffffff', '#4a90e2', ''],
        ['h_bandana_p', 'Bandana da pirata', 40, 'bandana', '#3a63c9', '#ffffff', ''],
        ['h_basco_rosso', 'Basco rosso', 50, 'beret', '#e63946', '', ''],
        ['h_basco_nero', 'Basco nero', 50, 'beret', '#2b2540', '', ''],
        ['h_bucket_blu', 'Cappello da pescatore blu', 50, 'bucket', '#4a90e2', '#2f63b0', ''],
        ['h_bucket_kaki', 'Cappello da pescatore kaki', 50, 'bucket', '#c9b27a', '#8a7a4a', ''],
        ['h_aviatore', 'Casco da aviatore', 90, 'pilot', '#a86a3a', '#2b2540', ''],
        ['h_cuffie_r', 'Cuffie rosse', 60, 'headphones', '#ff5a5f', '#2b2540', ''],
        ['h_cuffie_a', 'Cuffie azzurre', 60, 'headphones', '#53c8f5', '#2b2540', ''],
        ['cilindro', 'Cilindro', 120, 'tophat', '#2b2540', '#ff5a5f', ''],
        ['h_cilindro_gala', 'Cilindro da gala', 150, 'tophat', '#6a2fc4', '#ffd23f', ''],
        ['h_cilindro_verde', 'Cilindro fortunato', 130, 'tophat', '#1f8a4c', '#ffd23f', ''],
        ['h_bombetta', 'Bombetta', 90, 'bowler', '#2b2540', '#ff5a5f', ''],
        ['h_bombetta_m', 'Bombetta marrone', 90, 'bowler', '#7a4d22', '#d9a066', ''],
        ['h_fedora', 'Fedora marrone', 90, 'fedora', '#a86a3a', '#3a2a1a', ''],
        ['h_fedora_g', 'Fedora grigio', 90, 'fedora', '#8a91a0', '#2b2540', ''],
        ['h_gangster', 'Cappello da gangster', 100, 'fedora', '#2b2540', '#ffffff', ''],
        ['cowboy', 'Cowboy', 70, 'cowboy', '#c98a3b', '#6b3f14', ''],
        ['h_sceriffo', 'Cappello da sceriffo', 80, 'cowboy', '#f5f0e0', '#8a5a2b', ''],
        ['h_cowboy_nero', 'Cowboy nero', 80, 'cowboy', '#3a3450', '#c0392b', ''],
        ['sombrero', 'Sombrero', 70, 'sombrero', '#ffd25a', '#ff5a5f', '#ffb000'],
        ['h_sombrero_r', 'Sombrero rosso', 80, 'sombrero', '#ff6b6b', '#ffd23f', '#c0392b'],
        ['h_paglia', 'Cappello di paglia', 50, 'straw', '#f2d37a', '#ff5a5f', ''],
        ['h_panama', 'Panama', 80, 'straw', '#f6ecd0', '#2b2540', ''],
        ['festa', 'Cappello da festa', 50, 'party', '#ff6b9a', '#ffd23f', ''],
        ['h_festa_blu', 'Cono da festa blu', 50, 'party', '#53c8f5', '#ffd23f', ''],
        ['h_festa_oro', 'Cono da festa dorato', 60, 'party', '#ffd23f', '#ff5a5f', ''],
        ['mago_h', 'Cappello da mago', 100, 'wizard', '#7a4fd6', '#ffd23f', '#5b34b0'],
        ['h_mago_notte', 'Mago della notte', 110, 'wizard', '#2a3f9b', '#ffd23f', '#1b2a70'],
        ['h_strega', 'Cappello da strega', 110, 'wizard', '#2b2540', '#ff8c42', '#1f1a2e'],
        ['h_mago_rosso', 'Mago di fuoco', 110, 'wizard', '#d63f45', '#ffd23f', '#a4212a'],
        ['babbo', 'Babbo Natale', 120, 'santa', '#e63946', '#ffffff', ''],
        ['h_elfo', 'Cappello da elfo', 100, 'santa', '#2fa84f', '#ffd23f', ''],
        ['h_giullare', 'Giullare', 90, 'jester', '#e63946', '#2a3f9b', '#ffd23f'],
        ['h_giullare_v', 'Giullare viola', 90, 'jester', '#a67cf2', '#38d178', '#ffd23f'],
        ['h_zucca', 'Zucca di Halloween', 120, 'pumpkin', '#ff8c42', '#2fa84f', ''],
        ['h_fiori', 'Corona di fiori', 90, 'flowers', '#ff8fbf', '#ffd23f', '#ffffff'],
        ['h_girasoli', 'Corona di girasoli', 100, 'flowers', '#ffd23f', '#8a5a2b', '#ffb000'],
        ['h_alloro', 'Corona d\'alloro', 150, 'laurel', '#38b56a', '', ''],
        ['h_alloro_oro', 'Alloro d\'oro', 220, 'laurel', '#ffd23f', '', ''],
        ['corona', 'Corona d\'oro', 250, 'crown', '#ffd23f', '#ffb000', '#ff5a5f'],
        ['h_corona_arg', 'Corona d\'argento', 180, 'crown', '#dfe3ea', '#aeb4bf', '#4a90e2'],
        ['h_corona_bro', 'Corona di bronzo', 130, 'crown', '#d9a066', '#8a5a2b', '#ff5a5f'],
        ['h_corona_rub', 'Corona di rubini', 300, 'crown', '#ff6b81', '#a4133c', '#ffd23f'],
        ['h_aureola', 'Aureola', 200, 'halo', '#ffd23f', '', ''],
        ['h_coppa', 'Coppa dei campioni', 350, 'trophy', '#ffd23f', '#8a5a2b', ''],
        ['h_pallone', 'Pallone in testa', 120, 'ball', '', '', ''],
        ['h_fiamme', 'Testa in fiamme', 300, 'flame', '#ff8c42', '#ffd23f', ''],
        ['h_tocco', 'Tocco di laurea', 110, 'grad', '#2b2540', '#ffd23f', ''],
        ['vichingo', 'Elmo vichingo', 110, 'viking', '#b8bfcc', '#8a91a0', '#fff3d6'],
        ['h_vichingo_oro', 'Elmo vichingo dorato', 200, 'viking', '#ffd23f', '#ffb000', '#fff3d6'],
        ['pirata', 'Cappello da pirata', 90, 'pirate', '#2b2540', '#ffffff', ''],
        ['h_corsaro', 'Corsaro rosso', 100, 'pirate', '#c0392b', '#ffffff', ''],
        ['h_capitano_p', 'Capitano dei mari', 120, 'pirate', '#2a3f9b', '#ffd23f', ''],
        ['cuoco', 'Cappello da cuoco', 60, 'chef', '#ffffff', '#e6e6ee', ''],
        ['h_cuoco_nero', 'Cuoco stellato', 90, 'chef', '#3a3450', '#ff5a5f', ''],
        ['elica', 'Berretto con elica', 80, 'propeller', '#53c8f5', '#ffd23f', ''],
        ['h_elica_r', 'Elica rossa', 80, 'propeller', '#ff5a5f', '#ffffff', ''],
        ['h_elica_v', 'Elica verde', 80, 'propeller', '#38d178', '#ffd23f', ''],
        ['h_elmetto', 'Elmetto militare', 90, 'military', '#5b6b3a', '#3d4a28', ''],
        ['h_elmetto_s', 'Elmetto del deserto', 90, 'military', '#c9b27a', '#8a7a4a', ''],
        ['h_casco_giallo', 'Casco da cantiere', 60, 'hardhat', '#ffd23f', '#f0a800', ''],
        ['h_casco_arancio', 'Casco arancione', 60, 'hardhat', '#ff8c42', '#d9721a', ''],
        ['h_casco_bianco', 'Casco del caposquadra', 70, 'hardhat', '#ffffff', '#d9d9e3', ''],
        ['h_pompiere', 'Casco da pompiere', 100, 'fireman', '#e63946', '#ffd23f', ''],
        ['h_vigile', 'Berretto da vigile', 90, 'police', '#2a3f9b', '#1f1a2e', '#ffd23f'],
        ['h_poliziotto', 'Berretto da poliziotto', 90, 'police', '#2b2540', '#8a91a0', '#ffd23f'],
        ['h_marinaio', 'Cappello da marinaio', 70, 'sailor', '#ffffff', '#2a3f9b', ''],
        ['h_capitano', 'Berretto da capitano', 110, 'captain', '#f5f0e0', '#2a3f9b', ''],
        ['h_astronauta', 'Casco da astronauta', 200, 'astronaut', '#f5f5fa', '#ffb000', ''],
        ['h_cavaliere', 'Elmo da cavaliere', 140, 'knight', '#b8bfcc', '#ff5a5f', ''],
        ['h_cavaliere_o', 'Elmo del re', 250, 'knight', '#ffd23f', '#a67cf2', ''],
        ['h_turbante', 'Turbante', 90, 'turban', '#ff8c42', '#4a90e2', ''],
        ['h_fez', 'Fez rosso', 80, 'fez', '#c0392b', '#ffd23f', ''],
        ['h_birillo', 'Birillo stradale', 60, 'cone', '#ff8c42', '#2b2540', ''],
        ['h_gatto', 'Orecchie da gatto', 70, 'catears', '#2b2540', '#ff8fbf', '#ff8fbf'],
        ['h_gatta', 'Orecchie da gatta', 70, 'catears', '#ff8fbf', '#ffffff', '#e0568f'],
        ['h_coniglio', 'Orecchie da coniglio', 70, 'rabbit', '#ffffff', '#ff8fbf', ''],
        ['h_orso', 'Orecchie d\'orso', 70, 'bear', '#a86a3a', '#e0b98a', ''],
        ['h_renna', 'Corna di renna', 100, 'antlers', '#8a5a2b', '', ''],
        ['h_diavolo', 'Corna da diavolo', 120, 'devil', '#e63946', '#ff5a5f', ''],
        ['h_unicorno', 'Corno di unicorno', 160, 'unicorn', '#ffffff', '#ff8fbf', ''],
        ['h_unicorno_o', 'Corno d\'oro', 260, 'unicorn', '#ffd23f', '#ff8c42', ''],
        ['h_alieno', 'Antenne aliene', 100, 'alien', '#38d178', '', ''],
        ['h_fungo', 'Cappello di fungo', 90, 'mushroom', '#e63946', '#ffffff', ''],
        ['h_gelato', 'Gelato alla fragola', 90, 'icecream', '#ff8fbf', '#e0a458', ''],
        ['h_gelato_p', 'Gelato al pistacchio', 90, 'icecream', '#a8e6a3', '#e0a458', ''],
    ],
    'bg' => [
        ['pois', 'Pois rosa', 60],
        ['ghiaccio', 'Ghiaccio', 60],
        ['prato', 'Prato all\'inglese', 80],
        ['scacchi', 'Scacchiera', 100],
        ['fiamme', 'Fiamme', 120],
        ['arcobaleno', 'Arcobaleno', 150],
        ['notte', 'Notte di Champions', 150],
        ['galassia', 'Galassia', 200],
        ['oro', 'Oro colato', 250],
        ['g_tramonto', 'Tramonto', 60],
        ['g_oceano', 'Oceano', 70],
        ['g_foresta', 'Foresta', 60],
        ['g_lava', 'Lava', 150],
        ['g_aurora', 'Aurora boreale', 200],
        ['g_caramella', 'Caramella', 70],
        ['g_deserto', 'Deserto', 70],
        ['g_neve', 'Neve', 60],
        ['g_ciliegia', 'Ciliegia', 70],
        ['g_menta', 'Menta', 50],
        ['g_limone', 'Limone', 50],
        ['g_mirtillo', 'Mirtillo', 70],
        ['g_zebra', 'Zebra', 90],
        ['g_tigre', 'Tigre', 110],
        ['g_camo', 'Mimetico', 90],
        ['g_tartan', 'Tartan', 100],
        ['g_marinaio', 'Righe da marinaio', 60],
        ['g_mattoncini', 'Mattoncini', 80],
        ['g_damasco', 'Damasco', 130],
        ['g_onde', 'Onde', 90],
        ['g_scaglie', 'Scaglie', 110],
        ['g_triangoli', 'Triangoli', 90],
        ['g_zigzag', 'Zigzag', 80],
        ['g_rombi', 'Rombi', 90],
        ['g_bersaglio', 'Bersaglio', 80],
        ['g_raggi', 'Raggi di sole', 120],
        ['g_pixel', 'Pixel', 100],
        ['g_matrix', 'Matrix', 180],
        ['g_neon', 'Neon', 170],
        ['g_vaporwave', 'Vaporwave', 180],
        ['g_retro', 'Anni \'80', 100],
        ['g_disco', 'Discoteca', 160],
        ['g_carbonio', 'Fibra di carbonio', 220],
        ['g_marmo', 'Marmo', 200],
        ['g_legno', 'Legno', 80],
        ['g_jeans', 'Jeans', 90],
        ['g_argento', 'Argento', 220],
        ['g_bronzo', 'Bronzo', 180],
        ['g_rubino', 'Rubino', 320],
        ['g_smeraldo', 'Smeraldo', 320],
        ['g_zaffiro', 'Zaffiro', 320],
    ],
    'border' => [
        ['b_oro', 'Oro', 150],
        ['b_argento', 'Argento', 110],
        ['b_bronzo', 'Bronzo', 80],
        ['b_rubino', 'Rubino', 120],
        ['b_smeraldo', 'Smeraldo', 120],
        ['b_zaffiro', 'Zaffiro', 120],
        ['b_ametista', 'Ametista', 120],
        ['b_rosa', 'Rosa confetto', 70],
        ['b_nero', 'Nero pece', 60],
        ['b_bianco', 'Bianco neve', 60],
        ['b_arcobaleno', 'Arcobaleno', 180],
        ['b_fuoco', 'Fuoco', 160],
        ['b_ghiaccio', 'Ghiaccio', 130],
        ['b_tramonto', 'Tramonto', 130],
        ['b_oceano', 'Oceano', 130],
        ['b_neon_rosa', 'Neon rosa', 220],
        ['b_neon_azzurro', 'Neon azzurro', 220],
        ['b_neon_verde', 'Neon verde', 220],
        ['b_cantiere', 'Lavori in corso', 100],
        ['b_scacchi', 'Scacchi', 110],
        ['b_punti', 'Punti rosa', 90],
        ['b_candy', 'Bastoncino di zucchero', 100],
        ['b_greca', 'Greca dorata', 200],
        ['b_legno', 'Legno', 90],
        ['b_pietra', 'Pietra', 90],
        ['b_ferro', 'Ferro ribattuto', 110],
        ['b_diamante', 'Diamante', 350],
        ['b_elettrico', 'Scarica elettrica', 400],
        ['b_arcobaleno_a', 'Arcobaleno in movimento', 450],
        ['b_oro_pulsante', 'Oro pulsante', 500],
    ],
    'nick' => [
        ['treno', 'Il Treno', 40],
        ['puma', 'Il Puma', 40],
        ['muro', 'Il Muro', 50],
        ['furia', 'La Furia', 50],
        ['fenomeno', 'Il Fenomeno', 60],
        ['maestro', 'Il Maestro', 60],
        ['sultano', 'Il Sultano', 80],
        ['mago', 'Il Mago', 80],
        ['gladiatore', 'Il Gladiatore', 100],
        ['n_falco', 'Il Falco', 40],
        ['n_squalo', 'Lo Squalo', 50],
        ['n_cobra', 'Il Cobra', 50],
        ['n_bisonte', 'Il Bisonte', 60],
        ['n_saetta', 'La Saetta', 60],
        ['n_principe', 'Il Principe', 70],
        ['n_guerriero', 'Il Guerriero', 80],
        ['n_capitano', 'Il Capitano', 90],
        ['n_rapace', 'Il Rapace', null, ['goals', 5, '5 gol in totale']],
        ['bomber', 'Il Bomber', null, ['goals', 10, '10 gol in totale']],
        ['cecchino', 'Il Cecchino', null, ['goals', 25, '25 gol in totale']],
        ['n_cannoniere', 'Il Cannoniere', null, ['goals', 50, '50 gol in totale']],
        ['tripletta', 'Mister Tripletta', null, ['max_goals', 3, '3 gol in una sola partita']],
        ['n_poker', 'Il Poker', null, ['max_goals', 4, '4 gol in una sola partita']],
        ['n_suggeritore', 'Il Suggeritore', null, ['assists', 3, '3 assist in totale']],
        ['assistman', 'L\'Assistman', null, ['assists', 10, '10 assist in totale']],
        ['regista', 'Il Regista', null, ['assists', 25, '25 assist in totale']],
        ['n_genio', 'Il Genio', null, ['assists', 50, '50 assist in totale']],
        ['n_pistolero', 'Il Pistolero', null, ['ga', 20, '20 tra gol e assist']],
        ['n_promessa', 'La Promessa', null, ['mvp', 1, '1 premio MVP']],
        ['mvp', 'Mister MVP', null, ['mvp', 3, '3 premi MVP']],
        ['n_fuoriclasse', 'Il Fuoriclasse', null, ['mvp', 5, '5 premi MVP']],
        ['leggenda', 'La Leggenda', null, ['mvp', 10, '10 premi MVP']],
        ['n_dio', 'Il Dio del Calcetto', null, ['mvp', 20, '20 premi MVP']],
        ['n_esordiente', 'L\'Esordiente', null, ['apps', 1, '1 partita giocata']],
        ['colonna', 'La Colonna', null, ['apps', 15, '15 partite giocate']],
        ['veterano', 'Il Veterano', null, ['apps', 30, '30 partite giocate']],
        ['n_monumento', 'Il Monumento', null, ['apps', 60, '60 partite giocate']],
        ['vincente', 'Il Vincente', null, ['wins', 10, '10 vittorie']],
        ['n_trionfatore', 'Il Trionfatore', null, ['wins', 25, '25 vittorie']],
        ['n_inarrestabile', 'L\'Inarrestabile', null, ['streak', 5, '5 vittorie di fila']],
        ['n_sfortunato', 'Lo Sfortunato', null, ['losses', 10, '10 sconfitte (ma non molla)']],
        ['professore', 'Il Professore', null, ['top_avg', 7.5, 'media voto di 7,5 dopo almeno 5 partite']],
        ['n_impeccabile', 'L\'Impeccabile', null, ['top_avg', 8.0, 'media voto di 8 dopo almeno 5 partite']],
        ['traditore', 'Il Traditore', null, ['own_goals', 2, '2 autogol (sì, si sblocca anche così)']],
        ['n_autorete', 'Re dell\'Autogol', null, ['own_goals', 5, '5 autogol']],
        ['veggente', 'Il Veggente', null, ['bets_won', 5, '5 scommesse vinte']],
        ['n_indovino', 'L\'Indovino', null, ['bets_won', 15, '15 scommesse vinte']],
        ['riccone', 'Il Riccone', null, ['coins', 500, '500 gettoni in portafoglio']],
        ['n_magnate', 'Il Magnate', null, ['coins', 1000, '1000 gettoni in portafoglio']],
        ['n_collezionista', 'Il Collezionista', null, ['items', 10, '10 oggetti comprati nel negozio']],
    ],
];
