<?php
/*
 * Catalogo del negozio (lib/shop.php): copricapi, sfondi, bordi e nickname del profilo, e in fondo gli oggetti del Personaggio
 * (avatar.php), un oggetto per riga. Si può modificare a mano:
 *  - copricapi: [chiave, nome, prezzo, forma (lib/hats.php), colore a, b, c];
 *  - sfondi e bordi: [chiave, nome, prezzo] (il disegno sta in assets/style.css: classi bgp-<chiave> e brd-<chiave>);
 *  - nickname: [chiave, nome, prezzo] se si compra, oppure [chiave, nome, null, [statistica, soglia, descrizione]] se si sblocca con un obiettivo.
 * Le chiavi sono uniche in tutto il catalogo e lunghe al massimo 16 caratteri (finiscono nel database).
 */
return [
    'hat' => [
        ['cap', 'Cappellino rosso', 50, 'cap', '#ff5a5f', '#c93a40', ''],
        ['h_cap_blu', 'Cappellino blu', 50, 'cap', '#4a90e2', '#2f63b0', ''],
        ['h_cap_verde', 'Cappellino verde', 50, 'cap', '#38d178', '#23a85b', ''],
        ['h_cap_nero', 'Cappellino nero', 65, 'cap', '#3a3450', '#1f1a2e', ''],
        ['h_cap_rosa', 'Cappellino rosa', 50, 'cap', '#ff8fbf', '#e0568f', ''],
        ['h_visiera', 'Visiera bianca', 40, 'visor', '#ffffff', '#e0e0ea', ''],
        ['h_visiera_g', 'Visiera gialla', 40, 'visor', '#ffd23f', '#f0a800', ''],
        ['h_lana_rossa', 'Berretto di lana rosso', 50, 'beanie', '#ff5a5f', '#c93a40', '#ffffff'],
        ['h_lana_blu', 'Berretto di lana blu', 50, 'beanie', '#4a90e2', '#2f63b0', '#ffd23f'],
        ['h_lana_verde', 'Berretto di lana verde', 50, 'beanie', '#38d178', '#23a85b', '#ffffff'],
        ['h_lana_viola', 'Berretto di lana viola', 65, 'beanie', '#a67cf2', '#7a4fd6', '#ffd23f'],
        ['h_bandana_r', 'Bandana rossa', 40, 'bandana', '#ff5a5f', '#ffffff', ''],
        ['h_ninja', 'Fascia da ninja', 65, 'bandana', '#2b2540', '#c0c6d2', ''],
        ['h_fascia_sport', 'Fascia sportiva', 40, 'bandana', '#ffffff', '#4a90e2', ''],
        ['h_bandana_p', 'Bandana da pirata', 50, 'bandana', '#3a63c9', '#ffffff', ''],
        ['h_basco_rosso', 'Basco rosso', 65, 'beret', '#e63946', '', ''],
        ['h_basco_nero', 'Basco nero', 65, 'beret', '#2b2540', '', ''],
        ['h_bucket_blu', 'Cappello da pescatore blu', 65, 'bucket', '#4a90e2', '#2f63b0', ''],
        ['h_bucket_kaki', 'Cappello da pescatore kaki', 65, 'bucket', '#c9b27a', '#8a7a4a', ''],
        ['h_aviatore', 'Casco da aviatore', 115, 'pilot', '#a86a3a', '#2b2540', ''],
        ['h_cuffie_r', 'Cuffie rosse', 80, 'headphones', '#ff5a5f', '#2b2540', ''],
        ['h_cuffie_a', 'Cuffie azzurre', 80, 'headphones', '#53c8f5', '#2b2540', ''],
        ['cilindro', 'Cilindro', 190, 'tophat', '#2b2540', '#ff5a5f', ''],
        ['h_cilindro_gala', 'Cilindro da gala', 240, 'tophat', '#6a2fc4', '#ffd23f', ''],
        ['h_cilindro_verde', 'Cilindro fortunato', 210, 'tophat', '#1f8a4c', '#ffd23f', ''],
        ['h_bombetta', 'Bombetta', 115, 'bowler', '#2b2540', '#ff5a5f', ''],
        ['h_bombetta_m', 'Bombetta marrone', 115, 'bowler', '#7a4d22', '#d9a066', ''],
        ['h_fedora', 'Fedora marrone', 115, 'fedora', '#a86a3a', '#3a2a1a', ''],
        ['h_fedora_g', 'Fedora grigio', 115, 'fedora', '#8a91a0', '#2b2540', ''],
        ['h_gangster', 'Cappello da gangster', 160, 'fedora', '#2b2540', '#ffffff', ''],
        ['cowboy', 'Cowboy', 90, 'cowboy', '#c98a3b', '#6b3f14', ''],
        ['h_sceriffo', 'Cappello da sceriffo', 105, 'cowboy', '#f5f0e0', '#8a5a2b', ''],
        ['h_cowboy_nero', 'Cowboy nero', 105, 'cowboy', '#3a3450', '#c0392b', ''],
        ['sombrero', 'Sombrero', 90, 'sombrero', '#ffd25a', '#ff5a5f', '#ffb000'],
        ['h_sombrero_r', 'Sombrero rosso', 105, 'sombrero', '#ff6b6b', '#ffd23f', '#c0392b'],
        ['h_paglia', 'Cappello di paglia', 65, 'straw', '#f2d37a', '#ff5a5f', ''],
        ['h_panama', 'Panama', 105, 'straw', '#f6ecd0', '#2b2540', ''],
        ['festa', 'Cappello da festa', 65, 'party', '#ff6b9a', '#ffd23f', ''],
        ['h_festa_blu', 'Cono da festa blu', 65, 'party', '#53c8f5', '#ffd23f', ''],
        ['h_festa_oro', 'Cono da festa dorato', 80, 'party', '#ffd23f', '#ff5a5f', ''],
        ['mago_h', 'Cappello da mago', 160, 'wizard', '#7a4fd6', '#ffd23f', '#5b34b0'],
        ['h_mago_notte', 'Mago della notte', 175, 'wizard', '#2a3f9b', '#ffd23f', '#1b2a70'],
        ['h_strega', 'Cappello da strega', 175, 'wizard', '#2b2540', '#ff8c42', '#1f1a2e'],
        ['h_mago_rosso', 'Mago di fuoco', 175, 'wizard', '#d63f45', '#ffd23f', '#a4212a'],
        ['babbo', 'Babbo Natale', 190, 'santa', '#e63946', '#ffffff', ''],
        ['h_elfo', 'Cappello da elfo', 160, 'santa', '#2fa84f', '#ffd23f', ''],
        ['h_giullare', 'Giullare', 115, 'jester', '#e63946', '#2a3f9b', '#ffd23f'],
        ['h_giullare_v', 'Giullare viola', 115, 'jester', '#a67cf2', '#38d178', '#ffd23f'],
        ['h_zucca', 'Zucca di Halloween', 190, 'pumpkin', '#ff8c42', '#2fa84f', ''],
        ['h_fiori', 'Corona di fiori', 115, 'flowers', '#ff8fbf', '#ffd23f', '#ffffff'],
        ['h_girasoli', 'Corona di girasoli', 160, 'flowers', '#ffd23f', '#8a5a2b', '#ffb000'],
        ['h_alloro', 'Corona d\'alloro', 240, 'laurel', '#38b56a', '', ''],
        ['h_alloro_oro', 'Alloro d\'oro', 350, 'laurel', '#ffd23f', '', ''],
        ['corona', 'Corona d\'oro', 500, 'crown', '#ffd23f', '#ffb000', '#ff5a5f'],
        ['h_corona_arg', 'Corona d\'argento', 290, 'crown', '#dfe3ea', '#aeb4bf', '#4a90e2'],
        ['h_corona_bro', 'Corona di bronzo', 210, 'crown', '#d9a066', '#8a5a2b', '#ff5a5f'],
        ['h_corona_rub', 'Corona di rubini', 600, 'crown', '#ff6b81', '#a4133c', '#ffd23f'],
        ['h_aureola', 'Aureola', 320, 'halo', '#ffd23f', '', ''],
        ['h_coppa', 'Coppa dei campioni', 700, 'trophy', '#ffd23f', '#8a5a2b', ''],
        ['h_pallone', 'Pallone in testa', 190, 'ball', '', '', ''],
        ['h_fiamme', 'Testa in fiamme', 600, 'flame', '#ff8c42', '#ffd23f', ''],
        ['h_tocco', 'Tocco di laurea', 175, 'grad', '#2b2540', '#ffd23f', ''],
        ['vichingo', 'Elmo vichingo', 175, 'viking', '#b8bfcc', '#8a91a0', '#fff3d6'],
        ['h_vichingo_oro', 'Elmo vichingo dorato', 320, 'viking', '#ffd23f', '#ffb000', '#fff3d6'],
        ['pirata', 'Cappello da pirata', 115, 'pirate', '#2b2540', '#ffffff', ''],
        ['h_corsaro', 'Corsaro rosso', 160, 'pirate', '#c0392b', '#ffffff', ''],
        ['h_capitano_p', 'Capitano dei mari', 190, 'pirate', '#2a3f9b', '#ffd23f', ''],
        ['cuoco', 'Cappello da cuoco', 80, 'chef', '#ffffff', '#e6e6ee', ''],
        ['h_cuoco_nero', 'Cuoco stellato', 115, 'chef', '#3a3450', '#ff5a5f', ''],
        ['elica', 'Berretto con elica', 105, 'propeller', '#53c8f5', '#ffd23f', ''],
        ['h_elica_r', 'Elica rossa', 105, 'propeller', '#ff5a5f', '#ffffff', ''],
        ['h_elica_v', 'Elica verde', 105, 'propeller', '#38d178', '#ffd23f', ''],
        ['h_elmetto', 'Elmetto militare', 115, 'military', '#5b6b3a', '#3d4a28', ''],
        ['h_elmetto_s', 'Elmetto del deserto', 115, 'military', '#c9b27a', '#8a7a4a', ''],
        ['h_casco_giallo', 'Casco da cantiere', 80, 'hardhat', '#ffd23f', '#f0a800', ''],
        ['h_casco_arancio', 'Casco arancione', 80, 'hardhat', '#ff8c42', '#d9721a', ''],
        ['h_casco_bianco', 'Casco del caposquadra', 90, 'hardhat', '#ffffff', '#d9d9e3', ''],
        ['h_pompiere', 'Casco da pompiere', 160, 'fireman', '#e63946', '#ffd23f', ''],
        ['h_vigile', 'Berretto da vigile', 115, 'police', '#2a3f9b', '#1f1a2e', '#ffd23f'],
        ['h_poliziotto', 'Berretto da poliziotto', 115, 'police', '#2b2540', '#8a91a0', '#ffd23f'],
        ['h_marinaio', 'Cappello da marinaio', 90, 'sailor', '#ffffff', '#2a3f9b', ''],
        ['h_capitano', 'Berretto da capitano', 175, 'captain', '#f5f0e0', '#2a3f9b', ''],
        ['h_astronauta', 'Casco da astronauta', 320, 'astronaut', '#f5f5fa', '#ffb000', ''],
        ['h_cavaliere', 'Elmo da cavaliere', 225, 'knight', '#b8bfcc', '#ff5a5f', ''],
        ['h_cavaliere_o', 'Elmo del re', 500, 'knight', '#ffd23f', '#a67cf2', ''],
        ['h_turbante', 'Turbante', 115, 'turban', '#ff8c42', '#4a90e2', ''],
        ['h_fez', 'Fez rosso', 105, 'fez', '#c0392b', '#ffd23f', ''],
        ['h_kippah', 'Kippah', 250, 'kippah', '#ffffff', '#2a3f9b', ''],
        ['h_birillo', 'Birillo stradale', 80, 'cone', '#ff8c42', '#2b2540', ''],
        ['h_gatto', 'Orecchie da gatto', 90, 'catears', '#2b2540', '#ff8fbf', '#ff8fbf'],
        ['h_gatta', 'Orecchie da gatta', 90, 'catears', '#ff8fbf', '#ffffff', '#e0568f'],
        ['h_coniglio', 'Orecchie da coniglio', 90, 'rabbit', '#ffffff', '#ff8fbf', ''],
        ['h_orso', 'Orecchie d\'orso', 90, 'bear', '#a86a3a', '#e0b98a', ''],
        ['h_renna', 'Corna di renna', 160, 'antlers', '#8a5a2b', '', ''],
        ['h_diavolo', 'Corna da diavolo', 190, 'devil', '#e63946', '#ff5a5f', ''],
        ['h_unicorno', 'Corno di unicorno', 255, 'unicorn', '#ffffff', '#ff8fbf', ''],
        ['h_unicorno_o', 'Corno d\'oro', 520, 'unicorn', '#ffd23f', '#ff8c42', ''],
        ['h_alieno', 'Antenne aliene', 160, 'alien', '#38d178', '', ''],
        ['h_fungo', 'Cappello di fungo', 115, 'mushroom', '#e63946', '#ffffff', ''],
        ['h_gelato', 'Gelato alla fragola', 115, 'icecream', '#ff8fbf', '#e0a458', ''],
        ['h_gelato_p', 'Gelato al pistacchio', 115, 'icecream', '#a8e6a3', '#e0a458', ''],
        // bandierine su un'asta, colori il più possibile vicini a quelli veri: forma giusta per l'orientamento
        // (verticale, orizzontale o quella apposta per il Brasile) e non stemmi/dettagli, come le maglie "nazionale"
        ['f_italia', 'Bandiera Italia', 60, 'flag', '#008c45', '#ffffff', '#cd212a'],
        ['f_francia', 'Bandiera Francia', 60, 'flag', '#0055a4', '#ffffff', '#ef4135'],
        ['f_brasile', 'Bandiera Brasile', 60, 'flag_br', '#009739', '#fedd00', '#012169'],
        ['f_argentina', 'Bandiera Argentina', 60, 'flag_h', '#74acdf', '#ffffff', '#74acdf'],
        ['f_spagna', 'Bandiera Spagna', 60, 'flag_h2', '#aa151b', '#f1bf00', ''],
        ['f_germania', 'Bandiera Germania', 60, 'flag_h', '#1f1a2e', '#dd0000', '#ffce00'],
        ['f_portogallo', 'Bandiera Portogallo', 60, 'flag_pt', '#046a38', '#da291c', ''],
        ['f_olanda', 'Bandiera Olanda', 60, 'flag_h', '#ae1c28', '#ffffff', '#21468b'],
    ],
    'bg' => [
        ['pois', 'Pois rosa', 80],
        ['ghiaccio', 'Ghiaccio', 80],
        ['prato', 'Prato all\'inglese', 105],
        ['scacchi', 'Scacchiera', 160],
        ['fiamme', 'Fiamme', 190],
        ['arcobaleno', 'Arcobaleno', 240],
        ['notte', 'Notte di Champions', 240],
        ['galassia', 'Galassia', 320],
        ['oro', 'Oro colato', 500],
        ['g_tramonto', 'Tramonto', 80],
        ['g_oceano', 'Oceano', 90],
        ['g_foresta', 'Foresta', 80],
        ['g_lava', 'Lava', 240],
        ['g_aurora', 'Aurora boreale', 320],
        ['g_caramella', 'Caramella', 90],
        ['g_deserto', 'Deserto', 90],
        ['g_neve', 'Neve', 80],
        ['g_ciliegia', 'Ciliegia', 90],
        ['g_menta', 'Menta', 65],
        ['g_limone', 'Limone', 65],
        ['g_mirtillo', 'Mirtillo', 90],
        ['g_zebra', 'Zebra', 115],
        ['g_tigre', 'Tigre', 175],
        ['g_camo', 'Mimetico', 115],
        ['g_tartan', 'Tartan', 160],
        ['g_marinaio', 'Righe da marinaio', 80],
        ['g_mattoncini', 'Mattoncini', 105],
        ['g_damasco', 'Damasco', 210],
        ['g_onde', 'Onde', 115],
        ['g_scaglie', 'Scaglie', 175],
        ['g_triangoli', 'Triangoli', 115],
        ['g_zigzag', 'Zigzag', 105],
        ['g_rombi', 'Rombi', 115],
        ['g_bersaglio', 'Bersaglio', 105],
        ['g_raggi', 'Raggi di sole', 190],
        ['g_pixel', 'Pixel', 160],
        ['g_matrix', 'Matrix', 290],
        ['g_neon', 'Neon', 270],
        ['g_vaporwave', 'Vaporwave', 290],
        ['g_retro', 'Anni \'80', 160],
        ['g_disco', 'Discoteca', 255],
        ['g_carbonio', 'Fibra di carbonio', 350],
        ['g_marmo', 'Marmo', 320],
        ['g_legno', 'Legno', 105],
        ['g_jeans', 'Jeans', 115],
        ['g_argento', 'Argento', 350],
        ['g_bronzo', 'Bronzo', 290],
        ['g_rubino', 'Rubino', 640],
        ['g_smeraldo', 'Smeraldo', 640],
        ['g_zaffiro', 'Zaffiro', 640],
    ],
    'border' => [
        ['b_oro', 'Oro', 240],
        ['b_argento', 'Argento', 175],
        ['b_bronzo', 'Bronzo', 105],
        ['b_rubino', 'Rubino', 190],
        ['b_smeraldo', 'Smeraldo', 190],
        ['b_zaffiro', 'Zaffiro', 190],
        ['b_ametista', 'Ametista', 190],
        ['b_rosa', 'Rosa confetto', 90],
        ['b_nero', 'Nero pece', 80],
        ['b_bianco', 'Bianco neve', 80],
        ['b_arcobaleno', 'Arcobaleno', 290],
        ['b_fuoco', 'Fuoco', 255],
        ['b_ghiaccio', 'Ghiaccio', 210],
        ['b_tramonto', 'Tramonto', 210],
        ['b_oceano', 'Oceano', 210],
        ['b_neon_rosa', 'Neon rosa', 350],
        ['b_neon_azzurro', 'Neon azzurro', 350],
        ['b_neon_verde', 'Neon verde', 350],
        ['b_cantiere', 'Lavori in corso', 160],
        ['b_scacchi', 'Scacchi', 175],
        ['b_punti', 'Punti rosa', 115],
        ['b_candy', 'Bastoncino di zucchero', 160],
        ['b_greca', 'Greca dorata', 320],
        ['b_legno', 'Legno', 115],
        ['b_pietra', 'Pietra', 115],
        ['b_ferro', 'Ferro ribattuto', 175],
        ['b_diamante', 'Diamante', 700],
        ['b_elettrico', 'Scarica elettrica', 800],
        ['b_arcobaleno_a', 'Arcobaleno in movimento', 900],
        ['b_oro_pulsante', 'Oro pulsante', 1000],
    ],
    'nick' => [
        ['treno', 'Il Treno', 50],
        ['puma', 'Il Puma', 50],
        ['muro', 'Il Muro', 65],
        ['furia', 'La Furia', 65],
        ['fenomeno', 'Il Fenomeno', 80],
        ['maestro', 'Il Maestro', 80],
        ['sultano', 'Il Sultano', 105],
        ['mago', 'Il Mago', 105],
        ['gladiatore', 'Il Gladiatore', 160],
        ['n_falco', 'Il Falco', 50],
        ['n_squalo', 'Lo Squalo', 65],
        ['n_cobra', 'Il Cobra', 65],
        ['n_bisonte', 'Il Bisonte', 80],
        ['n_saetta', 'La Saetta', 80],
        ['n_principe', 'Il Principe', 90],
        ['n_guerriero', 'Il Guerriero', 105],
        ['n_capitano', 'Il Capitano', 115],
        ['n_rapace', 'Il Rapace', null, ['goals', 5, '5 gol in totale']],
        ['bomber', 'Il Bomber', null, ['goals', 10, '10 gol in totale']],
        ['cecchino', 'Il Cecchino', null, ['goals', 25, '25 gol in totale']],
        ['n_cannoniere', 'Il Cannoniere', null, ['goals', 50, '50 gol in totale']],
        ['tripletta', 'Mister Tripletta', null, ['max_goals', 3, '3 gol in una sola partita']],
        ['n_poker', 'Il Poker', null, ['max_goals', 4, '4 gol in una sola partita']],
        ['n_suggeritore', 'Il Suggeritore', null, ['assists', 3, '3 assist in totale']],
        ['assistman', 'L\'Assistman', null, ['assists', 10, '10 assist in totale']],
        ['regista', 'Il Regista', null, ['assists', 25, '25 assist in totale']],
        ['n_genio', 'Il Genio', null, ['assists', 50, '50 assist in totale']],
        ['n_pistolero', 'Il Pistolero', null, ['ga', 20, '20 tra gol e assist']],
        ['n_promessa', 'La Promessa', null, ['mvp', 1, '1 premio MVP']],
        ['mvp', 'Mister MVP', null, ['mvp', 3, '3 premi MVP']],
        ['n_fuoriclasse', 'Il Fuoriclasse', null, ['mvp', 5, '5 premi MVP']],
        ['leggenda', 'La Leggenda', null, ['mvp', 10, '10 premi MVP']],
        ['n_dio', 'Il Dio del Calcetto', null, ['mvp', 20, '20 premi MVP']],
        ['n_esordiente', 'L\'Esordiente', null, ['apps', 1, '1 partita giocata']],
        ['colonna', 'La Colonna', null, ['apps', 15, '15 partite giocate']],
        ['veterano', 'Il Veterano', null, ['apps', 30, '30 partite giocate']],
        ['n_monumento', 'Il Monumento', null, ['apps', 60, '60 partite giocate']],
        ['vincente', 'Il Vincente', null, ['wins', 10, '10 vittorie']],
        ['n_trionfatore', 'Il Trionfatore', null, ['wins', 25, '25 vittorie']],
        ['n_inarrestabile', 'L\'Inarrestabile', null, ['streak', 5, '5 vittorie di fila']],
        ['n_sfortunato', 'Lo Sfortunato', null, ['losses', 10, '10 sconfitte (ma non molla)']],
        ['professore', 'Il Professore', null, ['top_avg', 7.5, 'media voto di 7,5 dopo almeno 5 partite']],
        ['n_impeccabile', 'L\'Impeccabile', null, ['top_avg', 8.0, 'media voto di 8 dopo almeno 5 partite']],
        ['traditore', 'Il Traditore', null, ['own_goals', 2, '2 autogol (sì, si sblocca anche così)']],
        ['n_autorete', 'Re dell\'Autogol', null, ['own_goals', 5, '5 autogol']],
        ['veggente', 'Il Veggente', null, ['bets_won', 5, '5 scommesse vinte']],
        ['n_indovino', 'L\'Indovino', null, ['bets_won', 15, '15 scommesse vinte']],
        ['riccone', 'Il Riccone', null, ['coins', 500, '500 KOIN in portafoglio']],
        ['n_magnate', 'Il Magnate', null, ['coins', 1000, '1000 KOIN in portafoglio']],
        ['n_collezionista', 'Il Collezionista', null, ['items', 10, '10 oggetti comprati nel negozio']],
    ],
    /*
     * Personaggio (avatar.php, disegno in lib/avatar.php). Prezzo 0 = incluso per tutti, senza comprarlo.
     * Carnagione e colori naturali dei capelli sono sempre gratis.
     */
    // capelli: [chiave, nome, prezzo, acconciatura (lib/avatar_pixel_art.php: px_hair), descrizione]
    'hair' => [
        ['ha_classico', 'Taglio classico', 0, 'classic', 'Il primo taglio della tua carriera.'],
        ['ha_rasato', 'Rasato', 0, 'buzz', 'Zero pensieri, zero pettine.'],
        ['ha_pelato', 'Pelato', 0, 'bald', 'Aerodinamico: il pallone scivola meglio.'],
        ['ha_riga', 'Riga di lato', 60, 'side', 'Pettinato per la foto di squadra.'],
        ['ha_sfumato', 'Sfumatura', 90, 'fade', 'Appena uscito dal barbiere.'],
        ['ha_spettinato', 'Spettinato', 90, 'spiky', 'Sveglia suonata cinque minuti prima della partita.'],
        ['ha_ciuffo', 'Ciuffo', 150, 'quiff', 'Non si scompone neanche in rovesciata.'],
        ['ha_ricci', 'Ricci', 150, 'curly', 'Volume da fuoriclasse.'],
        ['ha_codino', 'Codino', 180, 'bun', 'Legati stretti prima del fischio d\'inizio.'],
        ['ha_lunghi', 'Capelli lunghi', 180, 'long', 'Al vento sulla fascia.'],
        ['ha_mullet', 'Mullet', 220, 'mullet', 'Anni \'80 davanti, festa dietro.'],
        ['ha_treccine', 'Treccine', 240, 'braids', 'Ci vogliono ore, si vedono da tutto il campo.'],
        ['ha_cresta', 'Cresta', 300, 'mohawk', 'Per chi entra in campo per farsi notare.'],
        ['ha_coda_alta', 'Coda alta', 200, 'ponytail', 'Legata stretta, non si muove nemmeno in sprint.'],
        ['ha_afro', 'Afro', 260, 'afro', 'Volume da fenomeno, si vede da tutta la tribuna.'],
    ],
    // colore dei capelli (anche sopracciglia e barba): [chiave, nome, prezzo, colore]
    'hair_color' => [
        ['hc_nero', 'Nero', 0, '#231a17'],
        ['hc_castano_s', 'Castano scuro', 0, '#4a2c1d'],
        ['hc_castano', 'Castano', 0, '#7a4a2a'],
        ['hc_rosso', 'Rosso', 0, '#b5471f'],
        ['hc_biondo', 'Biondo', 0, '#e0b24f'],
        ['hc_platino', 'Biondo platino', 0, '#f3e3b0'],
        ['hc_grigio', 'Brizzolato', 0, '#9a9aa6'],
        ['hc_blu', 'Blu elettrico', 120, '#3a63ff'],
        ['hc_rosa', 'Rosa', 120, '#ff6bb5'],
        ['hc_verde', 'Verde prato', 120, '#38d178'],
        ['hc_viola', 'Viola', 120, '#8a5cf6'],
        ['hc_oro', 'Oro', 300, '#ffc21a'],
    ],
    // carnagione: [chiave, nome, prezzo, colore]
    'skin' => [
        ['sk_1', 'Chiarissima', 0, '#ffe0c4'],
        ['sk_2', 'Chiara', 0, '#f6c9a3'],
        ['sk_3', 'Media', 0, '#e8b287'],
        ['sk_4', 'Olivastra', 0, '#d09a6c'],
        ['sk_5', 'Ambrata', 0, '#b07a4f'],
        ['sk_6', 'Scura', 0, '#8a5a36'],
        ['sk_7', 'Molto scura', 0, '#643f24'],
    ],
    // barba e baffi: [chiave, nome, prezzo, stile (lib/avatar_pixel_art.php: px_beards)]
    'beard' => [
        ['be_nessuna', 'Niente barba', 0, 'none'],
        ['be_accenno', 'Barba di tre giorni', 0, 'stubble'],
        ['be_baffi', 'Baffi', 80, 'moustache'],
        ['be_pizzetto', 'Pizzetto', 80, 'goatee'],
        ['be_capitano', 'Baffi e pizzetto', 120, 'captain'],
        ['be_piena', 'Barba piena', 160, 'full'],
    ],
    // occhiali: [chiave, nome, prezzo, stile (lib/avatar_pixel_art.php: px_glasses)]
    'glasses' => [
        ['gl_nessuno', 'Niente occhiali', 0, 'none'],
        ['gl_vista', 'Occhiali da vista', 60, 'round'],
        ['gl_sole', 'Occhiali da sole', 120, 'sun'],
        ['gl_sport', 'Occhiali sportivi', 150, 'sport'],
        ['gl_stelle', 'Occhiali a stella', 220, 'stars'],
        ['gl_cuore', 'Occhiali a cuore', 220, 'hearts'],
        ['gl_monocolo', 'Monocolo', 300, 'monocle'],
    ],
    // maglie: [chiave, nome, prezzo, tipo ('club'|'national'), colore primario, colore secondario, motivo (lib/avatar.php: avatar_patterns)]
    // le 'national' riprendono i colori delle divise più note, senza stemmi né loghi. Le maglie create dai giocatori stanno in custom_jerseys.
    'jersey' => [
        ['j_casa', 'Maglia da gioco', 0, 'club', '#2a3f9b', '#ffffff'],
        ['j_rossa', 'Maglia rossa', 40, 'club', '#c0392b', '#ffffff'],
        ['j_nera', 'Maglia nera', 40, 'club', '#1f1a2e', '#ffd23f'],
        ['j_biancoceleste', 'Maglia biancoceleste', 40, 'club', '#a6e6ff', '#ffffff', 'stripes_v'],
        ['j_giallorossa', 'Maglia giallorossa', 40, 'club', '#c0392b', '#ffd23f'],
        ['j_viola', 'Maglia viola', 50, 'club', '#7a4fd6', '#ffffff'],
        ['j_verdona', 'Maglia verdona', 50, 'club', '#1f8a4c', '#ffd23f'],
        ['j_rossonera', 'Maglia rossonera', 70, 'club', '#c0392b', '#1f1a2e', 'stripes_v'],
        ['j_nerazzurra', 'Maglia nerazzurra', 70, 'club', '#2a63c9', '#1f1a2e', 'stripes_v'],
        ['j_bianconera', 'Maglia bianconera', 70, 'club', '#ffffff', '#1f1a2e', 'stripes_v'],
        ['j_cerchiata', 'Maglia a cerchi', 70, 'club', '#1f8a4c', '#ffffff', 'stripes_h'],
        ['j_fascia', 'Maglia con la fascia', 90, 'club', '#ffffff', '#c0392b', 'sash'],
        ['j_meta', 'Maglia a metà', 90, 'club', '#ffd23f', '#2a3f9b', 'halves'],
        ['j_retro', 'Maglia retrò', 110, 'club', '#1f8a4c', '#ffd23f', 'sleeves'],
        ['n_italia', 'Nazionale Italia', 90, 'national', '#2a3f9b', '#ffffff'],
        ['n_brasile', 'Nazionale Brasile', 90, 'national', '#ffd23f', '#1f8a4c'],
        ['n_argentina', 'Nazionale Argentina', 90, 'national', '#a6e6ff', '#ffffff', 'stripes_v'],
        ['n_francia', 'Nazionale Francia', 90, 'national', '#1f2a5c', '#ffffff'],
        ['n_germania', 'Nazionale Germania', 90, 'national', '#ffffff', '#1f1a2e'],
        ['n_spagna', 'Nazionale Spagna', 90, 'national', '#c0392b', '#ffd23f'],
        ['n_portogallo', 'Nazionale Portogallo', 90, 'national', '#c0392b', '#1f8a4c'],
        ['n_olanda', 'Nazionale Olanda', 90, 'national', '#ff8c42', '#ffffff'],
        ['n_inghilterra', 'Nazionale Inghilterra', 90, 'national', '#ffffff', '#2a3f9b'],
        ['n_croazia', 'Nazionale Croazia', 110, 'national', '#ffffff', '#c0392b', 'halves'],
        ['n_giappone', 'Nazionale Giappone', 90, 'national', '#1f2a5c', '#c0392b'],
        ['n_messico', 'Nazionale Messico', 90, 'national', '#1f8a4c', '#ffffff'],
        ['n_usa', 'Nazionale USA', 90, 'national', '#2a3f9b', '#ffffff', 'sash'],
        ['n_svezia', 'Nazionale Svezia', 90, 'national', '#ffd23f', '#2a3f9b'],
        ['n_norvegia', 'Nazionale Norvegia', 90, 'national', '#c0392b', '#ffffff'],
        ['n_canada', 'Nazionale Canada', 90, 'national', '#c0392b', '#ffffff', 'sash'],
        ['j_smeraldo', 'Maglia smeraldo', 60, 'club', '#1f8a4c', '#ffd23f', 'sleeves'],
        ['j_corallo', 'Maglia corallo', 60, 'club', '#ff6b6b', '#ffffff', 'halves'],
        ['j_notte', 'Maglia notte stellata', 130, 'club', '#1f1a2e', '#a6e6ff', 'stripes_v'],
    ],
    // pantaloncini: [chiave, nome, prezzo, colore]
    'shorts' => [
        ['p_bianchi', 'Pantaloncini bianchi', 0, '#ffffff'],
        ['p_neri', 'Pantaloncini neri', 25, '#1f1a2e'],
        ['p_blu', 'Pantaloncini blu', 25, '#2a3f9b'],
        ['p_rossi', 'Pantaloncini rossi', 25, '#c0392b'],
        ['p_verdi', 'Pantaloncini verdi', 25, '#1f8a4c'],
        ['p_azzurri', 'Pantaloncini azzurri', 25, '#53c8f5'],
        ['p_oro', 'Pantaloncini oro', 60, '#ffd23f'],
    ],
    // scarpette: [chiave, nome, prezzo, colore]
    'shoes' => [
        ['s_nere', 'Scarpette nere', 0, '#1f1a2e'],
        ['s_bianche', 'Scarpette bianche', 30, '#ffffff'],
        ['s_rosse', 'Scarpette rosse', 40, '#ff5a5f'],
        ['s_blu', 'Scarpette blu', 40, '#3a63ff'],
        ['s_fluo', 'Scarpette fluo', 55, '#38d178'],
        ['s_rosa', 'Scarpette rosa', 55, '#ff8fbf'],
        ['s_arancio', 'Scarpette arancioni', 55, '#ff8c42'],
        ['s_oro', 'Scarpette dorate', 120, '#ffd23f'],
    ],
    // pet: [chiave, nome, prezzo, animale (lib/avatar_pixel_art.php: px_pets), colore a, colore b]
    'pet' => [
        ['pe_nessuno', 'Nessun pet', 0, 'none', '', ''],
        ['pe_pallino', 'Pallino', 120, 'ball', '', ''],
        ['pe_pulcino', 'Pulcino', 150, 'chick', '#ffd23f', '#ffb000'],
        ['pe_gatto', 'Gatto rosso', 220, 'cat', '#ff9a2e', '#ffffff'],
        ['pe_gatto_nero', 'Gatto nero', 240, 'cat', '#3a3450', '#ffffff'],
        ['pe_cane', 'Cane', 220, 'dog', '#c98a3b', '#fff3d6'],
        ['pe_pinguino', 'Pinguino', 260, 'penguin', '#2b2540', '#ffffff'],
        ['pe_pogona', 'Pogona', 240, 'pogona', '#d9a441', '#f2d9a0'],
        ['pe_pogona_cit', 'Pogona citrus', 260, 'pogona', '#ff9a2e', '#ffe0a8'],
        ['pe_pogona_hyp', 'Pogona hypo', 260, 'pogona', '#f2ead8', '#ffffff'],
        ['pe_pogona_red', 'Pogona rossa', 280, 'pogona', '#c8502e', '#f2b48a'],
        ['pe_pogona_ver', 'Pogona verde', 260, 'pogona', '#7fae4a', '#d8e8a8'],
        ['pe_pogona_lem', 'Pogona lemon', 280, 'pogona', '#ffe066', '#fff3b8'],
    ],
    // pose (come sta fermo il personaggio): [chiave, nome, prezzo, posa (lib/avatar_pixel.php: px_poses)]
    'pose' => [
        ['po_riposo', 'Riposo', 0, 'rest'],
        ['po_aperte', 'Braccia aperte', 40, 'open'],
        ['po_saluto', 'Saluto', 60, 'wave'],
        ['po_indica', 'Indica', 60, 'point'],
        ['po_vittoria', 'Vittoria', 120, 'victory'],
        ['po_cielo', 'Braccia al cielo', 160, 'up'],
    ],
    // esultanze: [chiave, nome, prezzo, esultanza (fotogrammi in lib/avatar_pixel.php: px_celebrations)]
    'celebration' => [
        ['c_pugno', 'Pugno al cielo', 0, 'fist-pump'],
        ['c_esultanza', 'Esultanza classica', 45, 'celebration'],
        ['c_bacio', 'Bacio alla maglia', 55, 'shirt-kiss'],
        ['c_saluto', 'Saluto militare', 70, 'salute'],
        ['c_dita', 'Dita al cielo (Messi)', 90, 'skyfingers'],
        ['c_inginocchio', 'Scivolata in ginocchio', 70, 'kneel'],
        ['c_danza', 'Balletto', 90, 'dance'],
        ['c_linguaccia', 'Linguaccia (Del Piero)', 110, 'tongue'],
        ['c_aeroplano', 'L\'aeroplanino (Montella)', 120, 'plane'],
        ['c_culla', 'La culla (Bebeto)', 120, 'cradle'],
        ['c_orecchio', 'Mano all\'orecchio (Luca Toni)', 130, 'ear'],
        ['c_ciuccio', 'Il ciuccio (Totti)', 140, 'thumb'],
        ['c_robot', 'Il robot (Crouch)', 150, 'robot'],
        ['c_inzaghi', 'La corsa alla Inzaghi', 160, 'inzaghi'],
        ['c_conserte', 'Braccia conserte (Mbappé)', 160, 'crossed'],
        ['c_cuore', 'Il cuore di Insigne', 180, 'heart'],
        ['c_mitraglia', 'La mitraglia (Batistuta)', 180, 'machinegun'],
        ['c_arciere', 'L\'arciere (Cavani)', 180, 'archer'],
        ['c_why', 'Why always me? (Balotelli)', 200, 'why'],
        ['c_milla', 'Danza alla bandierina (Milla)', 200, 'milla'],
        ['c_selfie', 'Il selfie (Totti)', 220, 'selfie'],
        ['c_tuffo', 'Il tuffo (Klinsmann)', 220, 'dive'],
        ['c_tardelli', 'L\'urlo di Tardelli', 250, 'tardelli'],
        ['c_zen', 'La meditazione (Haaland)', 250, 'zen'],
        ['c_ruota', 'La ruota', 260, 'cartwheel'],
        ['c_backflip', 'Backflip', 300, 'backflip'],
        ['c_siu', 'Siuuu (Cristiano Ronaldo)', 350, 'siu'],
        ['c_hernanes', 'Il salto di Hernanes', 600, 'hernanes'],
        // esultanze ispirate a giocatrici famose (stessi motori di animazione, solo il nome cambia)
        ['c_marta', 'Le dita al cielo di Marta', 90, 'skyfingers'],
        ['c_putellas', 'Il cuore di Putellas', 180, 'heart'],
        ['c_kerr', 'Il backflip di Sam Kerr', 300, 'backflip'],
        ['c_girelli', 'La corsa di Girelli', 160, 'inzaghi'],
        ['c_rapinoe', 'La posa di Rapinoe', 160, 'crossed'],
        ['c_hegerberg', 'La calma di Hegerberg', 250, 'zen'],
        ['c_gama', 'Il saluto della capitana Gama', 70, 'salute'],
        ['c_bonansea', 'Il pugno di Bonansea', 45, 'fist-pump'],
    ],
];
